# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaPrensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('a_confirmar', 'a_confirmar'), ('confirmado', 'confirmado'), ('reportado', 'reportado')], default='a_confirmar', max_length=100, no_check_for_status=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(null=True)),
                ('lugar', models.CharField(help_text='La dirección aproximada del siniestro. Ej: Ruta 5, Km 123', max_length=200)),
                ('provincia', models.CharField(choices=[('B', 'Buenos Aires'), ('K', 'Catamarca'), ('H', 'Chaco'), ('U', 'Chubut'), ('C', 'Ciudad Autónoma de Buenos Aires'), ('X', 'Córdoba'), ('W', 'Corrientes'), ('E', 'Entre Ríos'), ('P', 'Formosa'), ('Y', 'Jujuy'), ('L', 'La Pampa'), ('F', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('Q', 'Neuquén'), ('R', 'Río Negro'), ('A', 'Salta'), ('J', 'San Juan'), ('D', 'San Luis'), ('Z', 'Santa Cruz'), ('S', 'Santa Fe'), ('G', 'Santiago del Estero'), ('V', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'), ('T', 'Tucumán')], max_length=20)),
                ('posicion', geoposition.fields.GeopositionField(max_length=42)),
                ('mensaje', models.TextField(null=True)),
                ('cargado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('causa_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Causa')),
                ('referencias_prensa', models.ManyToManyField(to='data.ReferenciaPrensa')),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('fecha', models.DateField(help_text='En ocasiones, una victima puede fallecer dias despues del siniestro')),
                ('dni', models.CharField(max_length=10, null=True)),
                ('nacionalidad', models.CharField(default='argentina', max_length=50)),
                ('lugar_residencia', models.CharField(help_text='Donde vivia esta persona', max_length=50)),
                ('genero', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('otro', 'otro')], max_length=30)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('fotos', models.ManyToManyField(to='data.ReferenciaPrensa')),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Siniestro')),
            ],
        ),
    ]
